#!/bin/bash
#
# firstinst-late-98: First install init script
#
# chkconfig: 345 98 02
# description: First install init script

. /etc/init.d/functions
service_name=firstinst-late-98

if [ "$1" != "start" ] ; then
    exit 0
fi

/sbin/chkconfig ${service_name} off

action "Running ${service_name}" /usr/libexec/firstinst/firstinst-run-parts ${service_name}

RETVAL=$?
exit $RETVAL
