#!/bin/bash
#
# firstinst-early-02: First install init script
#
# chkconfig: 345 02 98
# description: First install init script

. /etc/init.d/functions
service_name=firstinst-early-02

if [ "$1" != "start" ] ; then
    exit 0
fi

/sbin/chkconfig ${service_name} off

action "Running ${service_name}" /usr/libexec/firstinst/firstinst-run-parts ${service_name}

RETVAL=$?
exit $RETVAL
